
package com.bloomberg.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PerSecurityWS", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PerSecurityWS {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitGetDataResponse
     */
    @WebMethod(action = "submitGetDataRequest")
    @WebResult(name = "submitGetDataResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitGetDataResponse submitGetDataRequest(
        @WebParam(name = "submitGetDataRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitGetDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveGetDataResponse
     */
    @WebMethod(action = "retrieveGetDataResponse")
    @WebResult(name = "retrieveGetDataResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetDataResponse retrieveGetDataResponse(
        @WebParam(name = "retrieveGetDataRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveGetDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitGetHistoryResponse
     */
    @WebMethod(action = "submitGetHistoryRequest")
    @WebResult(name = "submitGetHistoryResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitGetHistoryResponse submitGetHistoryRequest(
        @WebParam(name = "submitGetHistoryRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitGetHistoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveGetHistoryResponse
     */
    @WebMethod(action = "retrieveGetHistoryResponse")
    @WebResult(name = "retrieveGetHistoryResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetHistoryResponse retrieveGetHistoryResponse(
        @WebParam(name = "retrieveGetHistoryRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveGetHistoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitScheduledResponse
     */
    @WebMethod(action = "submitScheduledRequest")
    @WebResult(name = "submitScheduledResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitScheduledResponse submitScheduledRequest(
        @WebParam(name = "submitScheduledRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitScheduledRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveScheduledResponse
     */
    @WebMethod(action = "retrieveScheduledResponse")
    @WebResult(name = "retrieveScheduledResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveScheduledResponse retrieveScheduledResponse(
        @WebParam(name = "retrieveScheduledRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveScheduledRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitCancelResponse
     */
    @WebMethod(action = "submitCancelRequest")
    @WebResult(name = "submitCancelResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitCancelResponse submitCancelRequest(
        @WebParam(name = "submitCancelRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitCancelRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveCancelResponse
     */
    @WebMethod(action = "retrieveCancelResponse")
    @WebResult(name = "retrieveCancelResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveCancelResponse retrieveCancelResponse(
        @WebParam(name = "retrieveCancelRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveCancelRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.GetCorrectionsResponse
     */
    @WebMethod(action = "getCorrections")
    @WebResult(name = "getCorrectionsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public GetCorrectionsResponse getCorrections(
        @WebParam(name = "getCorrectionsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        GetCorrectionsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitGetFundamentalsResponse
     */
    @WebMethod(action = "submitGetFundamentalsRequest")
    @WebResult(name = "submitGetFundamentalsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitGetFundamentalsResponse submitGetFundamentalsRequest(
        @WebParam(name = "submitGetFundamentalsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitGetFundamentalsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveGetFundamentalsResponse
     */
    @WebMethod(action = "retrieveGetFundamentalsResponse")
    @WebResult(name = "retrieveGetFundamentalsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetFundamentalsResponse retrieveGetFundamentalsResponse(
        @WebParam(name = "retrieveGetFundamentalsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveGetFundamentalsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitGetCompanyResponse
     */
    @WebMethod(action = "submitGetCompanyRequest")
    @WebResult(name = "submitGetCompanyResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitGetCompanyResponse submitGetCompanyRequest(
        @WebParam(name = "submitGetCompanyRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitGetCompanyRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveGetCompanyResponse
     */
    @WebMethod(action = "retrieveGetCompanyResponse")
    @WebResult(name = "retrieveGetCompanyResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetCompanyResponse retrieveGetCompanyResponse(
        @WebParam(name = "retrieveGetCompanyRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveGetCompanyRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitGetActionsResponse
     */
    @WebMethod(action = "submitGetActionsRequest")
    @WebResult(name = "submitGetActionsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitGetActionsResponse submitGetActionsRequest(
        @WebParam(name = "submitGetActionsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitGetActionsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveGetActionsResponse
     */
    @WebMethod(action = "retrieveGetActionsResponse")
    @WebResult(name = "retrieveGetActionsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetActionsResponse retrieveGetActionsResponse(
        @WebParam(name = "retrieveGetActionsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveGetActionsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.GetPortfolioValidationResponse
     */
    @WebMethod(action = "getPortfolioValidation")
    @WebResult(name = "getPortfolioValidationResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public GetPortfolioValidationResponse getPortfolioValidation(
        @WebParam(name = "getPortfolioValidationRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        GetPortfolioValidationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitGetQuotesResponse
     */
    @WebMethod(action = "submitGetQuotesRequest")
    @WebResult(name = "submitGetQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitGetQuotesResponse submitGetQuotesRequest(
        @WebParam(name = "submitGetQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitGetQuotesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveGetQuotesResponse
     */
    @WebMethod(action = "retrieveGetQuotesResponse")
    @WebResult(name = "retrieveGetQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetQuotesResponse retrieveGetQuotesResponse(
        @WebParam(name = "retrieveGetQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveGetQuotesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitGetAllQuotesResponse
     */
    @WebMethod(action = "submitGetAllQuotesRequest")
    @WebResult(name = "submitGetAllQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitGetAllQuotesResponse submitGetAllQuotesRequest(
        @WebParam(name = "submitGetAllQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitGetAllQuotesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveGetAllQuotesResponse
     */
    @WebMethod(action = "retrieveGetAllQuotesResponse")
    @WebResult(name = "retrieveGetAllQuotesResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveGetAllQuotesResponse retrieveGetAllQuotesResponse(
        @WebParam(name = "retrieveGetAllQuotesRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveGetAllQuotesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitOtcbvalUploadResponse
     */
    @WebMethod(action = "submitOtcbvalUploadRequest")
    @WebResult(name = "submitOtcbvalUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitOtcbvalUploadResponse submitOtcbvalUploadRequest(
        @WebParam(name = "submitOtcbvalUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitOtcbvalUploadRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveOtcbvalUploadResponse
     */
    @WebMethod(action = "retrieveOtcbvalUploadResponse")
    @WebResult(name = "retrieveOtcbvalUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveOtcbvalUploadResponse retrieveOtcbvalUploadResponse(
        @WebParam(name = "retrieveOtcbvalUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveOtcbvalUploadRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitOtcBvalDealsUploadResponse
     */
    @WebMethod(action = "submitOtcBvalDealsUploadRequest")
    @WebResult(name = "submitOtcBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitOtcBvalDealsUploadResponse submitOtcBvalDealsUploadRequest(
        @WebParam(name = "submitOtcBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitOtcBvalDealsUploadRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveOtcBvalDealsUploadResponse
     */
    @WebMethod(action = "retrieveOtcBvalDealsUploadResponse")
    @WebResult(name = "retrieveOtcBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveOtcBvalDealsUploadResponse retrieveOtcBvalDealsUploadResponse(
        @WebParam(name = "retrieveOtcBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveOtcBvalDealsUploadRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.GetFieldsResponse
     */
    @WebMethod(action = "getFields")
    @WebResult(name = "getFieldsResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public GetFieldsResponse getFields(
        @WebParam(name = "getFieldsRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        GetFieldsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.SubmitMmktBvalDealsUploadResponse
     */
    @WebMethod(action = "submitMmktBvalDealsUploadRequest")
    @WebResult(name = "submitMmktBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public SubmitMmktBvalDealsUploadResponse submitMmktBvalDealsUploadRequest(
        @WebParam(name = "submitMmktBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        SubmitMmktBvalDealsUploadRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bloomberg.ws.RetrieveMmktBvalDealsUploadResponse
     */
    @WebMethod(action = "retrieveMmktBvalDealsUploadResponse")
    @WebResult(name = "retrieveMmktBvalDealsUploadResponse", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "result")
    public RetrieveMmktBvalDealsUploadResponse retrieveMmktBvalDealsUploadResponse(
        @WebParam(name = "retrieveMmktBvalDealsUploadRequest", targetNamespace = "http://services.bloomberg.com/datalicense/dlws/ps/20071001", partName = "parameters")
        RetrieveMmktBvalDealsUploadRequest parameters);

}
